# Auto-Generated by /home/elias.souza/lineage/device/samsung/universal7885-common/generate_product_makefiles.py
$(call inherit-product, device/samsung/a10/full_a10.mk)
$(call inherit-product, vendor/lineage/config/common_full_phone.mk)
#$(call inherit-product, vendor/lineage/config/common.mk)

PRODUCT_NAME := lineage_a10

TARGET_BOOT_ANIMATION_RES := 720
#TARGET_USES_MINI_GAPPS := true
