# Auto-Generated by device/samsung/a20e/setup.sh
$(call inherit-product, device/samsung/a20e/full_a20e.mk)
$(call inherit-product, vendor/aosp/config/common.mk)
PRODUCT_NAME := aosp_a20e

# Additional Props
TARGET_FACE_UNLOCK_SUPPORTED := true
TARGET_BOOT_ANIMATION_RES := 720
